# Generated by Django 4.1 on 2022-08-22 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kanbanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kanbanapp.role'),
        ),
    ]
