# Generated by Django 4.1 on 2022-08-22 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanbanapp', '0002_users_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 41, 5, 1720)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 41, 5, 1720)),
        ),
        migrations.AlterField(
            model_name='project_roles',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 41, 4, 999871)),
        ),
        migrations.AlterField(
            model_name='project_roles',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 41, 4, 999871)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 41, 4, 998353)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 23, 41, 4, 998353)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 41, 4, 998353)),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 41, 4, 992388)),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 41, 4, 992388)),
        ),
        migrations.AlterField(
            model_name='statues',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 41, 4, 998873)),
        ),
        migrations.AlterField(
            model_name='statues',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 41, 4, 998873)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 41, 5, 872)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 41, 5, 872)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 41, 4, 993576)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_by',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 41, 4, 993576)),
        ),
    ]
