# Generated by Django 4.1 on 2022-08-22 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanbanapp', '0003_alter_comments_created_at_alter_comments_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='project_roles',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project_roles',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='statues',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='statues',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 23, 42, 57, 92539)),
        ),
    ]
