# Generated by Django 4.1 on 2022-08-23 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanbanapp', '0004_remove_comments_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role_id',
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 23, 5, 26, 37, 367159, tzinfo=datetime.timezone.utc)),
        ),
    ]
