# Generated by Django 4.1 on 2022-08-23 05:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kanbanapp', '0005_remove_users_role_id_alter_projects_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kanbanapp.role'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 23, 5, 36, 50, 699535, tzinfo=datetime.timezone.utc)),
        ),
    ]
