# Generated by Django 4.1 on 2022-08-23 05:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kanbanapp', '0006_users_role_id_alter_projects_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='avatar_image_url',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='background_image_url',
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 23, 5, 48, 17, 476013, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kanbanapp.role'),
        ),
    ]
