# Generated by Django 4.1 on 2022-08-23 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kanbanapp', '0007_remove_projects_avatar_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statues',
            name='css_style',
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 23, 7, 6, 58, 529925, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kanbanapp.statues'),
        ),
    ]
