# Generated by Django 4.1 on 2022-08-23 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanbanapp', '0008_remove_statues_css_style_alter_projects_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 23, 7, 20, 36, 429102, tzinfo=datetime.timezone.utc)),
        ),
    ]
