# Generated by Django 4.1 on 2022-08-23 07:28

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanbanapp', '0009_alter_projects_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 23, 7, 28, 10, 872575, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='assignee_id',
        ),
        migrations.AddField(
            model_name='tasks',
            name='assignee_id',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
