# Generated by Django 4.1 on 2022-08-23 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanbanapp', '0010_alter_projects_start_date_remove_tasks_assignee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 23, 7, 44, 50, 411684, tzinfo=datetime.timezone.utc)),
        ),
    ]
