# Generated by Django 4.1 on 2022-08-24 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kanbanapp', '0011_rename_desciption_tasks_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comment', to='Kanbanapp.tasks'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 24, 17, 9, 24, 688049, tzinfo=datetime.timezone.utc)),
        ),
    ]
