# Generated by Django 4.1 on 2022-09-03 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanbanapp', '0012_alter_comments_task_id_alter_projects_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=364)),
            ],
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='priority',
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 3, 3, 25, 46, 72850, tzinfo=datetime.timezone.utc)),
        ),
    ]
