# Generated by Django 4.1 on 2022-09-03 03:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kanbanapp', '0013_priority_remove_tasks_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kanbanapp.priority'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 3, 3, 30, 52, 447728, tzinfo=datetime.timezone.utc)),
        ),
    ]
